### ISSUE TITLE
combination with another js plugin

### ISSUE THREAD

**Issue by ivopivo72** [ian-de-vries/Multi-Screen.js#1]
first, sorry for my english...
i have a problem in combination with another js plugin, isotope.js.
after loaded "right" page, set of pictures in isotope gallery remain aligned in one column, after window resize is compared to right position.
can you help me?
look at example : http://ekrazit.cz/jancizi/
thank you

**Comment by ian-de-vries** [comment]
Hi ivopivo72,

Thanks for using my plugin - I hope you like it. 

As for the problem you're having, I can only guess that it has to do with the way you set up the Isotope.js plugin and should not be caused by interaction with Multi-Screen.js. With the Multi-Screen.js plugin, each (invisible) screen is loaded immediately when the user enters your page, just like any normal page would be. From what I could tell by looking at the Isotope.js homepage, your default layout may be set to "straightDown" which creates the single column effect you are seeing.

In case you are not convinced that Multi-Screen.js is not causing the problem, I would suggest that you try your "right" screen (with the Isotope.js content) as a standalone page without using Multi-Screen.js to see if the problem still occurs. If this seems to solve the problem, please let me know and I will take a closer look.

I hope this helps!

Best,

Ian de Vries

P.S. You should probably change the title of your page - it is still "Multi-Screen.js Demo" in case you had not noticed!
