### ISSUE TITLE
Transitions jumpy and out of place

### ISSUE THREAD

**Issue by quatlin** [ian-de-vries/Multi-Screen.js#2]
Hi Ian, 
Firstly, thanks for the great plugin, it's really useful! 
I'm just having some issues with the transitions from div to div, my content is centered, but while it's transitioning it jumps to the left as if it has no positioning, then it jumps back to it's correct position when the animation finishes. The transitions are also erratically jumpy on and off. Is there anything I might be missing? I think I followed the instructions to the letter. Any help is appreciated, thanks!

**Comment by ian-de-vries** [comment]
Hi Quatlin,

Thanks for giving Multi-Screen.js a try, I hope you can get it to work for your project.

For every animation, the plugin plays with the positioning settings of the leaving and entering screens (changing the screen to show to be absolute, and the leaving screen to be fixed) which may affect the centering of your elements. How are you centering your content in each div? In the demo page of the plugin, you'll notice the content is centered as well, without any animation issues. One thing I do there in the CSS is this:

html, body {
    width: 100%;
    height: 100%;
}

This forces the page to always be at least the size of the screen and may solve issues where the body size automatically shrinks to zero because during the duration of the animation there is no "absolute" positioned content to show.

If you have some sample code to share anywhere, I would be happy to help debug.

Best,

Ian
